In [19]:
#Nome do aluno: Davi dos Santos Lima
#RA: 5152118
#Atividade: Exercicio 3

In [20]:
#Importando as bibliotecas

import cv2
from google.colab.patches import cv2_imshow ### para imshow
from PIL import Image
from google.colab import drive
import matplotlib.pyplot as plt
import numpy as np
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


# 3) Operações com as matrizes: soma, valor máximo e mínimo.

In [52]:
x2 = np.random.randint(10, size=(3, 4))

In [53]:
print(x2)

[[5 3 5 6]
 [8 7 5 0]
 [4 0 7 1]]


#### a) Pode-se obter a soma de todos os elementos da matriz usando:  M1 = np.sum(x2)

In [54]:
M1 = np.sum(x2)
print(M1)

51


#### b) Vetor mostrando os valores máximos de cada coluna de uma 

In [55]:
matriz: M1 = x2.max(axis=0) 
print(matriz)

[8 7 7 6]


#### c) Valor máximo de uma matriz:

In [56]:
M2 = np.max(x2) 
print(M2)

8


#### d) Vetor mostrando os valores mínimos de cada coluna de uma matriz:

In [57]:
M3 = x2.min(axis=0)
print(M3)

[4 0 5 0]


#### e) Valor mínimo de uma matriz: 

In [58]:
M4 = np.min(x2) 
print(M4)

0


#### f) Dada a matriz 
 E = [ 1, 2, 3, 4; 
 5, 6, 7, 8; 
 9, 10, 11, 12; 
 13, 14, 15, 16]

In [59]:
E = np.array([[ 1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print(E)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


##### i) Criar a matriz F como uma cópia de E, sem a última linha e coluna

In [60]:
F = (E[:3,:3])
print(F)

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]


##### ii) Somar “+1” em todos os elementos pares da matriz E

In [100]:
G = np.array(E)

soma_vetor = lambda x:  x+1 if x%2 == 0 else x
    
H = np.array([soma_vetor(n) for n in np.nditer(G)]).reshape([4,4])

print(H)


[[ 1  3  3  5]
 [ 5  7  7  9]
 [ 9 11 11 13]
 [13 15 15 17]]


##### iii) Remova a primeira coluna de E

In [79]:
J = (E[:4,1:4])
print(J)

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]
