In [1]:
#Nome do aluno: Davi dos Santos Lima
#RA: 5152118
#Atividade: Exercicio 5

In [2]:
#Importando as bibliotecas

import cv2
from google.colab.patches import cv2_imshow ### para imshow
from google.colab import drive
import matplotlib.pyplot as plt
import numpy as np
from PIL import Image
from random import randint
from random import random 
from random import seed
from google.colab import drive  

drive.mount('/content/gdrive')

Mounted at /content/gdrive


# 5) No CoLab você pode gerar arranjos padrões que são úteis em diversas aplicações:

##### b) zeros(M,N) à matriz de zeros;
##### c) ones(M,N) à matriz de uns; 
##### d) full(M,N) à matriz de True e False; 
##### e) random() à matriz de números aleatórios inteiro em intervalos definidos  ouuniformemente distribuídos no intervalo [0,1]; 
##### f) randn(N) cria uma matriz de forma especificada e a preenche com valores  aleatórios conforme a distribuição normal padrão; 


##### g) Explique cada um desses comandos e comente os resultados. 

In [3]:
# I. Z1 = np.zeros((5,), dtype=int) 
Z1 = np.zeros((5,), dtype=int) 
print(Z1)

[0 0 0 0 0]


# <mark>Comentários</mark>

<dl>
  <dt>np.zeros((5,):</dt>
  <dd>É a primeira parte da função, onde a gente configura o tamanho ou o formato de um array que vai ser criado. Esse array conterá apenas zeros [0]. No nosso exemplo temos um array simples de 5 posições.</dd>
  <dt>, dtype=int):</dt>
  <dd>É a segunda parte da função, onde a gente configura o tipo do formato do dado que será retornado. No nosso exemplo o tipo será inteiro.</dd>

</dl>

> O código irá criar um array simples contendo 0 com o tamanho que foi configurado e com o tipo de formato configurado.

In [4]:
#II. Z2= np.ones(5)
Z2= np.ones(5)
print(Z2)

[1. 1. 1. 1. 1.]


# <mark>Comentários</mark>

<dl>
  <dt>np.ones(5):</dt>
  <dd>A ideia é a mesma do comando anterior: criar um array e poder configurá-lo de acordo com os parâmetros que forem colocados na função. No caso dessa função será um array com 5 posições preenchidas apenas pelo número 1.</dd>
</dl>


In [5]:
#III. value = randint(2, 5)
value = randint(2, 5)
print(value)

2


# <mark>Comentários</mark>

<dl>
  <dt>randint(2, 5):</dt>
  <dd>Essa função recebe 2 parâmetros numéricos e retorna um número aleatório entre eles, incluso eles mesmos. No exemplo temos 2 e 5, então o retorno será entre esses dois números.</dd>
</dl>


In [6]:
#IV. seed(1) 
seed(10) 
print(random())

0.5714025946899135


# <mark>Comentários</mark>

<dl>
  <dt>seed(1):</dt>
  <dd>O método seed seta um valor inicial para a função random. Então sempre que iniciamos o método seed com algum número, a função random vai retornar sempre o mesmo número gerado aleatóriamente.</dd>
</dl>

In [7]:
#V. print(random())
print(random()) 

0.4288890546751146


# <mark>Comentários</mark>

<dl>
  <dt>print(random())</dt>
  <dd>O método gera um número aleatório entre 0 e 1, seguindo a diretriz de ser uma distribuição normal (Gaussiana) de média 0 e variância 1. No caso do exemplo, ele vai gerar um array de 5 números seguindo esse critério. O método print imprime esse número na tela.</dd>
</dl>

In [8]:
#VI. np.random.randn(5) 
print(np.random.randn(5))

[ 2.52542595 -0.27567173 -0.28030233  0.31859324 -0.58742921]
