In [ ]:
#Nome do aluno: Davi dos Santos Lima
#RA: 5152118
#Atividade: Exercicio 1 e 2

In [ ]:
#Importando as bibliotecas

import cv2
from google.colab.patches import cv2_imshow ### para imshow
from PIL import Image
from google.colab import drive
import matplotlib.pyplot as plt
import numpy as np
drive.mount('/content/gdrive')

Mounted at /content/gdrive


# Exercicio 1

Digitar os arrays diretamente nos seguintes formatos e verificar os resultados. Para  visualizar o resultado use o comando “print”. Para a matriz “C” deve ser importado a  biblioteca “numpy” com o seguinte comando: “import numpy as np”.  


In [ ]:
A = [[1, 4, 5, 12], [-5, 8, 9, 0], [-6, 7, 11, 19]]
B = [[16, 8, 2, 4], [5, 7, 8, 11], [20, 30, 40, 50]]
C = np.array([[1, 2, 3], [3, 4, 5]])
D = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 8, 8, 9], [8, 7, 7, 8], [4, 5, 9, 8]] 

In [ ]:
print(f'A = {A}\n')
print(f'B = {B}\n')
print(f'C = {C}\n')
print(f'D = {D}\n')

A = [[1, 4, 5, 12], [-5, 8, 9, 0], [-6, 7, 11, 19]]

B = [[16, 8, 2, 4], [5, 7, 8, 11], [20, 30, 40, 50]]

C = [[1 2 3]
 [3 4 5]]

D = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 8, 8, 9], [8, 7, 7, 8], [4, 5, 9, 8]]



# Exercico 2
Verificar os resultados de cada linha com as matrizes construídas com objetivo de explorar a indexação.
a) Para selecionar um determinado elemento da matriz deve-se utilizar:  A[i, j] sendo i número da linha e j o número da coluna com i,j = 0, ...n-1.  Exemplo: Elemento da linha 0 e coluna

#### 1: AI = (A[0][1]) print(AI) 

In [ ]:
Ai = (A[0][1])
print(Ai)
Ai = (A[0][0])
print(Ai)
Ai = (A[1][1])
print(Ai)
Ai = (A[2][0])
print(Ai)

4
1
8
-6


In [ ]:
Bi = (B[0][0])
print(Bi)
Bi = (B[0][1])
print(Bi)
Bi = (B[1][0])
print(Bi)
Bi = (B[2][1])
print(Bi)

16
8
5
30


In [ ]:
Ci = (C[0][0])
print(Ci)
Ci = (C[0][1])
print(Ci)
Ci = (C[1][0])
print(Ci)
Ci = (C[1][1])
print(Ci)

1
2
3
4


In [ ]:
Di = (D[0][0])
print(Di)
Di = (D[0][1])
print(Di)
Di = (D[1][0])
print(Di)
Di = (D[1][1])
print(Di)

1
2
5
6


#### b) Usar os dois pontos (:) para representar “todos” ou “até”.  
Exemplos:
Todos os elementos da coluna 0:  
x2 = np.random.randint(10, size=(3, 4))  
print(x2[:, 0])


In [ ]:
x2 = np.random.randint(10, size=(3, 4))  

In [ ]:
print(x2)

[[5 4 2 5]
 [1 8 6 5]
 [2 7 1 6]]


Todos os elementos da primeira linha 0:

In [ ]:
print(x2[:, 1])

[4 8 7]


Todos os elementos da linha 0 até a linha 2 e da coluna 2 até a coluna 3:  print(x2[0:2, 2:3]) 

In [ ]:
print(x2[0:2, 2:3])

[[2]
 [6]]


Fazer todos os elementos da coluna 0 iguais a zero: 

In [ ]:
A4 = x2  
A4[: ,0] = 0

print(A4)

[[0 4 2 5]
 [0 8 6 5]
 [0 7 1 6]]


O elemento da última linha e última coluna:

In [ ]:
A5 = x2[-1,-1] 
print(A5)

6


Todos os elementos da última coluna:

In [ ]:
A6 = x2[: , -1]
print(A6)

[5 5 6]


O elemento da última linha e primeira coluna antes da última:  

In [ ]:
A7 = x2[-1, -2] 
print(A7)

1


Matriz transposta de x2:

In [ ]:
A9 = np.transpose(x2)
print(A9)

[[0 0 0]
 [4 8 7]
 [2 6 1]
 [5 5 6]]


#### c) Criar um vetor contendo:

i) Todos os valores de 1 a 20

In [ ]:
listA = np.arange(1, 21, 1, dtype=int)
print(listA)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


ii) Todos os valores pares de 1 a 20

In [ ]:
listB = np.arange(2, 21, 2, dtype=int)
print(listB)

[ 2  4  6  8 10 12 14 16 18 20]


iii) Todos os valores ímpares de 1 a 20;

In [ ]:
listC = np.arange(1, 21, 2, dtype=int)
print(listC)

[ 1  3  5  7  9 11 13 15 17 19]


iv) Valores de 0 a 1, intervalados de 0.1

In [ ]:
listD = np.arange(1, 20.01, 0.1, dtype=float)
print(listD)

[ 1.   1.1  1.2  1.3  1.4  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3
  2.4  2.5  2.6  2.7  2.8  2.9  3.   3.1  3.2  3.3  3.4  3.5  3.6  3.7
  3.8  3.9  4.   4.1  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5.   5.1
  5.2  5.3  5.4  5.5  5.6  5.7  5.8  5.9  6.   6.1  6.2  6.3  6.4  6.5
  6.6  6.7  6.8  6.9  7.   7.1  7.2  7.3  7.4  7.5  7.6  7.7  7.8  7.9
  8.   8.1  8.2  8.3  8.4  8.5  8.6  8.7  8.8  8.9  9.   9.1  9.2  9.3
  9.4  9.5  9.6  9.7  9.8  9.9 10.  10.1 10.2 10.3 10.4 10.5 10.6 10.7
 10.8 10.9 11.  11.1 11.2 11.3 11.4 11.5 11.6 11.7 11.8 11.9 12.  12.1
 12.2 12.3 12.4 12.5 12.6 12.7 12.8 12.9 13.  13.1 13.2 13.3 13.4 13.5
 13.6 13.7 13.8 13.9 14.  14.1 14.2 14.3 14.4 14.5 14.6 14.7 14.8 14.9
 15.  15.1 15.2 15.3 15.4 15.5 15.6 15.7 15.8 15.9 16.  16.1 16.2 16.3
 16.4 16.5 16.6 16.7 16.8 16.9 17.  17.1 17.2 17.3 17.4 17.5 17.6 17.7
 17.8 17.9 18.  18.1 18.2 18.3 18.4 18.5 18.6 18.7 18.8 18.9 19.  19.1
 19.2 19.3 19.4 19.5 19.6 19.7 19.8 19.9 20. ]
